apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: yourdomain-com-tls # k8s-multi-com-tls
spec:
  secretName: yourdomain-com # k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yourdomain.com # k8s-multi.com
  dnsNames:
  - yourdomain.com # k8s-multi.com
  - www.yourdomain.com # www.k8s-multi.com
